### PR TITLE
Supporting %{pattern:name:type} syntax

### PR DESCRIPTION
**Pull request by moebiuseye**
Attempt at addressing issue #17

### CODE REVIEW

**Comment by garyelephant** [comment]
Thanks for the code. Could you please add some test code in `tests/test_pygrok.py` to test `%{pattern:name:type}` syntax

**Comment by moebiuseye** [comment]
Of course! :)

**Comment by garyelephant** [comment]
logstash-filter-grok will convert string to `int` or `float` if you specify type conversion in grok pattern.
For example: `%{NUMBER:n1:int} %{NUMBER:n2:float}`, when grok match finished, `n1`'s type will be int, and `n2`'s type will be float.

I think you also need to add type conversion related code and update your test code.

**Comment by moebiuseye** [comment]
I hope this isn't too heavy...

**Comment by moebiuseye** [comment]
I'd be happy to read your comments on this.

**Comment by garyelephant** [comment]
Thanks @moebiuseye

**Pull request merged**
